myName=input("Your Name")
print("Thanks for logging in")
print(myName)
cardNumber = input("What is your credit card number?")
print("Thanks, I definitely won't put", cardNumber, 
"into Amazon and order anything weird")
print()
print("I Promise")
maidenName=input("What is your Mother's maiden name? ")
print()
print("That's cool, I just wanted to know that", maidenName, "was your Mum's maiden name. Not because the bank requested it or anything, honest.")