myName=input("Who are you?:")
print("So, you are")
print(myName)
myAge=input("How old are you?:")
print("and are the ripe old age of")
print(myAge)
git=input("How do you feel about working in git?:")
print("and clearly think that git is")
print(git)